name: Setti's
markdown: redcarpet
pygments: true
permalink: /:categories/:title
exclude:
    - README.md
    - LICENSE

redcarpet:
  extensions:
    - quote
    - footnotes
    - fenced_code_blocks
    - autolink
    - tables

